import { ICommand } from "@nova-x-ai/core";

export class CreateCharacterCommand implements ICommand {
    constructor(
        public readonly name: string,
        public readonly title: string,
        public readonly biography: string,
        public readonly tagline: string,
        public readonly occupation: string,
        public readonly age: string = "",
        public readonly origin: string = "",
        public readonly gender: string = "",
        public readonly role: string = "",
        public readonly language: string = "",
        public readonly dialectNotes: string[] = [],
        public readonly tags: string[] = [],
        public readonly visualDescription: string = "",
        public readonly clothingStyle: string = "casual",
        public readonly distinguishingMarks: string = "",
        public readonly skinTone: string = "",
        public readonly faceCharacteristics: string = "",
        public readonly bodyType: string = "",
        public readonly bodySize: string = "",
        public readonly height: string = "",
        public readonly hairStyle: string = "",
        public readonly hairLength: string = "",
        public readonly hairColor: string = "",
        public readonly eyeCharacteristics: string = "",
        public readonly eyeColor: string = "",
        public readonly accessories: string[] = [],
        public readonly personalityDescription: string = "",
        public readonly speakingStyle: string = "",
        public readonly tone: string = "neutral",
        public readonly interests: string[] = [],
        public readonly likes: string[] = [],
        public readonly dislikes: string[] = [],
        public readonly background: string = "",
        public readonly relationshipStyle: string = "",
        public readonly goals: string[] = [],
        public readonly customInstructions: string = "",
        public readonly moralAlignment: string = "neutral",
        public readonly quirks: string[] = [],
        public readonly fears: string[] = [],
        public readonly desires: string[] = [],
        public readonly traits: Array<{ name: string; score: number }> = [],
        public readonly ownerId: string,
        public readonly claims: { roles: string[]; permissions: string[] }
    ) {}
}
