import type { IEventBus } from "@nova-x-ai/core";
import type { IVoiceRepository } from "../Domain/Repositories/IVoiceRepository";
import type { IVoiceSessionRepository } from "../Domain/Repositories/IVoiceSessionRepository";
import type { IVoiceProfileRepository } from "../Domain/Repositories/IVoiceProfileRepository";
import type { IVoiceEventStoreRepository } from "../Domain/Repositories/IVoiceEventStoreRepository";
import type { IScheduledVoiceTaskRepository } from "../Domain/Repositories/IScheduledVoiceTaskRepository";
import type { ITimeSimulationService } from "../Domain/Services/ITimeSimulationService";
import type { IAudioCompressionService } from "../Domain/Services";
import type { IVoiceCacheService } from "../Domain/Services";
import type { IMultiSpeakerCoordinator } from "../Domain/Services";
import { VoiceAggregate } from "../Domain/Aggregates/VoiceAggregate";
import { VoiceProfile } from "../Domain/Entities/VoiceProfile";
import { VoiceId } from "../Domain/ValueObjects/VoiceId";
import { VoiceSessionId } from "../Domain/ValueObjects/VoiceSessionId";
import { VoiceProfileId } from "../Domain/ValueObjects/VoiceProfileId";
import { VoiceStateRef } from "../Domain/ValueObjects/VoiceState";
import { VoiceSessionStateRef } from "../Domain/ValueObjects/VoiceSessionState";
import { AudioChunkSequence } from "../Domain/ValueObjects/AudioChunkSequence";
import { AudioSampleRate } from "../Domain/ValueObjects/AudioSampleRate";
import { AudioBitDepth } from "../Domain/ValueObjects/AudioBitDepth";
import { AudioCodec } from "../Domain/ValueObjects/AudioCodec";
import { AudioDuration } from "../Domain/ValueObjects/AudioDuration";
import { VoiceProviderId } from "../Domain/ValueObjects/VoiceProviderId";
import { VoiceLocale } from "../Domain/ValueObjects/VoiceLocale";
import { ProviderCostMetadata } from "../Domain/ValueObjects/ProviderCostMetadata";
import { AudioChunk } from "../Domain/ValueObjects/AudioChunk";
import { PCMBuffer } from "../Domain/ValueObjects/PCMBuffer";

export interface IVoiceEngine {
    readonly eventBus: IEventBus;
    readonly voiceRepository: IVoiceRepository;
    readonly sessionRepository: IVoiceSessionRepository;
    readonly profileRepository: IVoiceProfileRepository;
    readonly eventStoreRepository: IVoiceEventStoreRepository;
    readonly scheduledTaskRepository: IScheduledVoiceTaskRepository;
    readonly timeSimulationService: ITimeSimulationService;
    readonly audioCompressionService: IAudioCompressionService;
    readonly voiceCacheService: IVoiceCacheService;
    readonly multiSpeakerCoordinator: IMultiSpeakerCoordinator;

    initialize(voiceId: string): Promise<void>;
    synthesizeSpeech(command: import("../Application/Commands/SynthesizeSpeechCommand").SynthesizeSpeechCommand): Promise<import("../Application/DTO/AudioStreamHandleDto").AudioStreamHandleDto>;
    interrupt(command: import("../Application/Commands/InterruptCommand").InterruptCommand): Promise<void>;
    pause(command: import("../Application/Commands/PauseCommand").PauseCommand): Promise<void>;
    resume(command: import("../Application/Commands/ResumeCommand").ResumeCommand): Promise<void>;
    cancelStream(command: import("../Application/Commands/CancelStreamCommand").CancelStreamCommand): Promise<void>;
    regenerateAudio(command: import("../Application/Commands/RegenerateAudioCommand").RegenerateAudioCommand): Promise<import("../Application/DTO/AudioStreamHandleDto").AudioStreamHandleDto>;
    retryUtterance(command: import("../Application/Commands/RetryUtteranceCommand").RetryUtteranceCommand): Promise<import("../Application/DTO/AudioStreamHandleDto").AudioStreamHandleDto>;
    createVoiceProfile(command: import("../Application/Commands/CreateVoiceProfileCommand").CreateVoiceProfileCommand): Promise<void>;
    updateVoiceProfile(command: import("../Application/Commands/UpdateVoiceProfileCommand").UpdateVoiceProfileCommand): Promise<void>;
    deleteVoiceProfile(command: import("../Application/Commands/DeleteVoiceProfileCommand").DeleteVoiceProfileCommand): Promise<void>;
    scheduleVoiceTask(command: import("../Application/Commands/ScheduleVoiceTaskCommand").ScheduleVoiceTaskCommand): Promise<void>;
    getVoiceProfile(query: import("../Application/Queries/GetVoiceProfileQuery").GetVoiceProfileQuery): Promise<import("../Application/DTO/VoiceProfileDto").VoiceProfileDto>;
    getVoiceSession(query: import("../Application/Queries/GetVoiceSessionQuery").GetVoiceSessionQuery): Promise<import("../Application/DTO/VoiceSessionDto").VoiceSessionDto>;
    getAudioStream(query: import("../Application/Queries/GetAudioStreamQuery").GetAudioStreamQuery): Promise<import("../Application/DTO/AudioStreamDto").AudioStreamDto>;
    listVoiceProfiles(query: import("../Application/Queries/ListVoiceProfilesQuery").ListVoiceProfilesQuery): Promise<import("../Application/DTO/VoiceProfileSummaryDto").VoiceProfileSummaryDto[]>;
    getSynthesisStatus(query: import("../Application/Queries/GetSynthesisStatusQuery").GetSynthesisStatusQuery): Promise<import("../Application/DTO/VoiceSynthesisResultDto").VoiceSynthesisResultDto>;
    getProviderHealth(query: import("../Application/Queries/GetProviderHealthQuery").GetProviderHealthQuery): Promise<import("../Application/DTO/ProviderHealthDto").ProviderHealthDto>;
    getAudioCache(query: import("../Application/Queries/GetAudioCacheQuery").GetAudioCacheQuery): Promise<import("../Application/DTO/AudioCacheDto").AudioCacheDto>;
    takeSnapshot(voiceId: string): Promise<object>;
    shutdown(): Promise<void>;
}
